name: Awaken Your Senses
favicon: null
layout_spectrum: 0.99872
typography_spectrum: 0.9499303172342479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8dfce'
    - '#a588a4'
    - '#a7c48c'
    - '#e9b67d'
    - '#6c965d'
  brandStrength: 0.75
  lightness: 0.3146030504722148
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
